# Generated by Django 3.1.3 on 2020-12-27 11:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousDegree',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('college_id', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PUResult',
            fields=[
                ('pu_roll', models.CharField(default='909090', max_length=6, primary_key=True, serialize=False)),
                ('marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='marks')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2020)], verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('ph_number', models.CharField(default='for existing', max_length=10)),
                ('email', models.EmailField(default='for existing', max_length=254)),
                ('address', models.CharField(default='for existing', max_length=300)),
                ('bc_number', models.CharField(default='for existing', max_length=10)),
                ('adhaar_number', models.CharField(default='for existing', max_length=50)),
                ('dob', models.DateField(default=datetime.date(2020, 12, 27))),
                ('pu_roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.puresult')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KCETResult',
            fields=[
                ('rank', models.IntegerField(default='1400', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1400)], verbose_name='rank')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='FormLastActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVerified',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('username', models.CharField(max_length=50)),
                ('verified', models.BooleanField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
