# Generated by Django 3.1.3 on 2020-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentverified',
            name='username',
        ),
        migrations.AddField(
            model_name='documentverified',
            name='unique_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
